### ISSUE TITLE
mutations in derivations, parsing, etc

### ISSUE THREAD

**Issue by fvkd** [mcdonc/p51-thinkpad-nixos#1]
thank you so much for the awesome videos and tutorials. i appreciate the humor as well. you're keepin' it positive despite the hip injury =) anyway, I haven't caught up yet to Episode 17, but i did notice just now, you were commenting about derivations not turning out exactly replicated. have you used a parser at all yet? apparently unparsed derivations and dervs that have been run thru different parsers/etc are causing some mutations. if you do run your stuff through a parser, which do you favor? 
I've been favoring Alejandra so far.

**Comment by mcdonc** [comment]
Yikes sorry, I missed this when it came in originally (my GitHub notifications are a horrow show).

No, I don't run my derivations through a parser.  As far as I understand it (and I might be misunderstanding the question), the Nix *source* representation of a derivation produces the same .drv no matter what its structure is (whitespace, ordering, etc). I do use the "format buffer" command in emacs pretty often when editing .nix files.

Thanks for the comment!
